// Package interactions is the daemon's task store: a single durable log of the delegation
// interactions this daemon is part of, in EITHER role. It is what lets an agent be only intermittently
// online — the daemon persists inbound tasks (so a provider whose external agent is offline still
// accepts and stores work) and outbound delegations (so a requester can read the result later), and
// both survive daemon restarts. Each interaction carries a multi-turn conversation (the message table).
//
// One SQLite table (+ a per-interaction message log), one row per interaction, discriminated by role:
//   - RoleInbound  — someone delegated a task TO us; we are the provider. The provider completes a
//     text task on its own (A2A-DESIGN §4.2) and signs a receipt over the transcript. anet itself
//     runs no model — the deliverable comes from the operator's EXTERNAL agent.
//   - RoleOutbound — WE delegated a task to a provider; we are the requester. We converse, then
//     receive the result + the provider's receipt and may attach our signed review.
//
// The task state (A2A-DESIGN §4.1) is written by the event that causes it, never derived from the
// conversation: every write goes through a guarded UPDATE that refuses to leave a terminal state,
// and increments state_seq so a waiter can tell a new state event from the value it already saw.
//
// interaction_id is generated by the REQUESTER at delegate time and carried on the wire, so both
// daemons key the same interaction by the same id — that shared id is what the receipt and the review
// bind to.
package interactions

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"

	_ "modernc.org/sqlite" // pure-Go driver (A3: no cgo in distributed runtime)
)

// ErrBadInput is returned for missing required fields.
var ErrBadInput = errors.New("interactions: invalid input")

// ErrNotFound is returned when no interaction has the given id.
var ErrNotFound = errors.New("interactions: not found")

// ErrTerminal is returned by a state write against an interaction that is
// already in a terminal state. The row is left unchanged: a completed task
// is not canceled afterwards, a canceled one is not completed, and a
// receipt is never stored on a canceled interaction.
var ErrTerminal = errors.New("interactions: interaction is in a terminal state")

// Role is this daemon's side of an interaction.
type Role string

const (
	RoleInbound  Role = "inbound"  // someone delegated to us (we are the provider)
	RoleOutbound Role = "outbound" // we delegated to a provider (we are the requester)
)

// State is an interaction's task state (A2A-DESIGN §4.1). The strings are
// the A2A TaskState names in lowercase-hyphen form.
type State string

const (
	StateSubmitted     State = "submitted"
	StateWorking       State = "working"
	StateInputRequired State = "input-required"
	StateCompleted     State = "completed"
	StateFailed        State = "failed"
	StateCanceled      State = "canceled"
	StateRejected      State = "rejected"
)

// terminalSQL is the SQL list of terminal states. It is the only place the
// guarded writes name them; IsTerminal is its Go counterpart and a test
// keeps the two equal.
const terminalSQL = `('completed','failed','canceled','rejected')`

// IsTerminal reports whether s is one of the four terminal states. Every
// "has this task ended" check in the daemon goes through it.
func (s State) IsTerminal() bool {
	switch s {
	case StateCompleted, StateFailed, StateCanceled, StateRejected:
		return true
	}
	return false
}

// Valid reports whether s is one of the seven defined states.
func (s State) Valid() bool {
	switch s {
	case StateSubmitted, StateWorking, StateInputRequired,
		StateCompleted, StateFailed, StateCanceled, StateRejected:
		return true
	}
	return false
}

// Trust is how an inbound interaction was admitted (A2A-DESIGN §5.2). It is
// empty for an outbound interaction.
const (
	TrustPeer      = "peer"       // the requester is on the allow (or trust) list
	TrustPublic    = "public"     // a natural-language task accepted under the open policy
	TrustPublicCap = "public_cap" // a call to one of this node's public capabilities
	TrustApproved  = "approved"   // held in the pending queue and approved by the operator
)

// Values of the pay_state column (A2A-DESIGN §4.1). Written by the payment
// flow; listed here so the value domain is defined next to the column.
const (
	PayNone      = ""          // no quote
	PayRequired  = "required"  // quoted (provider) or quote received (requester)
	PaySubmitted = "submitted" // provider: payload persisted, awaiting settlement; requester: payment-submitted sent
	PayCompleted = "completed" // settled
	PayFailed    = "failed"    // settlement definitely failed
	PayRejected  = "rejected"  // the requester declined to pay
)

// Message kinds carried in the per-interaction conversation log.
const (
	MsgText       = "text"        // a normal chat message
	MsgEndRequest = "end_request" // the requester asks the provider to complete the task
	// MsgEndAccept is a historical kind. From wire 2 the provider completes on its own and no
	// daemon sends it; rows written before the change keep it.
	MsgEndAccept = "end_accept"
	MsgCancel    = "cancel"  // a cancellation request
	MsgStatus    = "status"  // a provider status update (anet.status/1)
	MsgPayment   = "payment" // an x402 payment message; only its metadata is stored
)

// Message is one entry in an interaction's conversation log. The sealed envelope it arrived in
// was signed by its sender (A2A-DESIGN §3.3); the log itself stores no signature.
type Message struct {
	Seq           int64
	InteractionID string
	SenderAID     string
	Kind          string // MsgText | MsgEndRequest | MsgCancel | MsgStatus | MsgPayment | MsgEndAccept
	Body          string
	// MsgID is the sender-minted message id. The sender stores its own id too, so both sides can
	// replay a history with message ids (A2A Message.messageId).
	MsgID string
	// Metadata is the message's JSON metadata object, or empty.
	Metadata  string
	CreatedAt string
}

// Attachment is one binary payload (image / media / archive) attached to a conversation message. The
// bytes are stored inline in SQLite (v0.1); integrity is pinned by CID = anetcid.SumRaw(Data). List/read
// helpers return metadata WITHOUT Data unless a data-loading accessor is used, to keep thread rendering
// and transcript building cheap.
type Attachment struct {
	Seq           int64
	InteractionID string
	MsgSeq        int64 // the message (message.seq) this attachment belongs to
	Name          string
	Mime          string
	Size          int64
	CID           string
	Data          []byte // populated only by AttachmentData
	CreatedAt     string
}

// Interaction is one stored delegation record.
type Interaction struct {
	Seq        int64  // local monotonic cursor
	ID         string // shared interaction_id (requester-generated)
	Role       Role
	PeerAID    string // the OTHER party: provider (outbound) or requester (inbound)
	Goal       string // the task text (for a public capability call: the capability id)
	State      State
	StateAt    int64 // unix ms of the last state write
	StateSeq   int64 // incremented by every state write
	RequestCID string
	RequestDoc []byte // the signed request TaskDoc bytes (Sum == RequestCID)
	ResultCID  string
	Result     []byte // the deliverable/transcript bytes
	Receipt    []byte // provider-signed receipt object (evidence.Receipt.Marshal)
	Review     []byte // requester-signed review object (evidence.Review.Marshal), outbound only
	// ReceiptVerified says whether this node could check the receipt that
	// came with the result: Verified, Unverified, or Unknown for a row
	// written before this was recorded. Three states, not two — a
	// completion nobody could audit is not the same as one that failed
	// an audit, and neither is the same as one that passed.
	ReceiptVerified Verification
	EndReqBy        string // historical: AID that requested ending ("" = none)
	EndAccBy        string // historical: AID that accepted (wire 1 only)
	ContextID       string
	Trust           string // TrustPeer | TrustPublic | TrustPublicCap | TrustApproved; "" for outbound
	IsCapability    bool
	TaskNonce       string // base64url of the TaskDoc's anet.nonce context
	PayState        string
	PayRequired     []byte // x402 PaymentRequired JSON
	PayAuthIDs      []string
	PayPayload      []byte
	PayReceipts     []byte // JSON array of settlement responses
	QuoteExpiresAt  int64  // unix ms
	// PeerKEL and PeerKeys hold the requester's KEL and SignedEncKeySet for
	// a public or public_cap interaction, whose peer is not recorded in
	// peer_identity (A2A-DESIGN §3.8). They are deleted when the
	// interaction reaches a terminal state.
	PeerKEL   []byte
	PeerKeys  []byte
	CreatedAt string // RFC3339Nano
	UpdatedAt string // RFC3339Nano

	// ResultMeta is the metadata object the result carried (anet.reason,
	// anet.retry_after_ms, anet.effect_status, x402 keys), as JSON, or "".
	// The deliverable is what the receipt covers; this is what the result
	// said about it, kept so a later reader — the A2A projection — can
	// still say why a task was refused and when to retry.
	ResultMeta string
}

// IsTerminal reports whether the interaction's state is terminal.
func (ix *Interaction) IsTerminal() bool { return ix != nil && ix.State.IsTerminal() }

// Verification is the three-state answer to "could this node check the
// receipt?". The zero value is Unknown on purpose: a row that predates
// this column, or any path that forgets to say, reads as "we do not
// know" rather than as either verdict.
type Verification string

const (
	VerificationUnknown    Verification = ""
	VerificationVerified   Verification = "verified"
	VerificationUnverified Verification = "unverified"
)

// Store is the daemon's interaction log.
type Store struct {
	db *sql.DB
	mu sync.Mutex // serializes writes (single writer); reads run lock-free under WAL
	// peerCap bounds the unpinned peer_identity rows (see peers.go).
	peerCap int
	// refusedCaps bounds the refused table; refusedRows counts its rows
	// once refusedCounted (see refused.go). Both under mu.
	refusedCaps    RefusedCaps
	refusedRows    int
	refusedCounted bool
	// now is the clock for state_at; tests replace it.
	now func() int64
}

// Open opens (creating if needed) an interactions store at dir (SQLite at dir/interactions.db).
func Open(dir string) (*Store, error) {
	if dir == "" {
		return nil, fmt.Errorf("interactions: dir required")
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return nil, fmt.Errorf("interactions: mkdir: %w", err)
	}
	db, err := sql.Open("sqlite", filepath.Join(dir, "interactions.db")+"?_pragma=journal_mode(WAL)&_pragma=synchronous(NORMAL)&_pragma=busy_timeout(15000)")
	if err != nil {
		return nil, fmt.Errorf("interactions: open db: %w", err)
	}
	s := &Store{db: db}
	if err := s.migrate(); err != nil {
		db.Close()
		return nil, err
	}
	return s, nil
}

// Close closes the db handle.
func (s *Store) Close() error { return s.db.Close() }

// SetClock replaces the clock used for state_at (unix ms). Tests only.
func (s *Store) SetClock(now func() int64) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.now = now
}

func (s *Store) nowMS() int64 {
	if s.now != nil {
		return s.now()
	}
	return time.Now().UnixMilli()
}

// interactionColumns are the columns of a fresh interaction table, and the
// columns an existing table is brought up to. Order matters only for the
// CREATE statement.
var interactionAdded = []struct{ name, decl string }{
	{"receipt_verified", "TEXT NOT NULL DEFAULT ''"},
	{"end_req_by", "TEXT NOT NULL DEFAULT ''"},
	{"end_acc_by", "TEXT NOT NULL DEFAULT ''"},
	{"state", "TEXT NOT NULL DEFAULT 'submitted'"},
	{"state_at", "INTEGER NOT NULL DEFAULT 0"},
	{"state_seq", "INTEGER NOT NULL DEFAULT 0"},
	{"context_id", "TEXT NOT NULL DEFAULT ''"},
	{"trust", "TEXT NOT NULL DEFAULT ''"},
	{"is_capability", "INTEGER NOT NULL DEFAULT 0"},
	{"task_nonce", "TEXT NOT NULL DEFAULT ''"},
	{"pay_state", "TEXT NOT NULL DEFAULT ''"},
	{"pay_required", "BLOB"},
	{"pay_auth_ids", "TEXT NOT NULL DEFAULT ''"},
	{"pay_payload", "BLOB"},
	{"pay_receipts", "BLOB"},
	{"quote_expires_at", "INTEGER NOT NULL DEFAULT 0"},
	{"peer_kel", "BLOB"},
	{"peer_keys", "BLOB"},
	{"result_meta", "TEXT NOT NULL DEFAULT ''"},
}

func (s *Store) migrate() error {
	stmts := []string{
		`CREATE TABLE IF NOT EXISTS interaction (
		   seq INTEGER PRIMARY KEY AUTOINCREMENT,
		   id TEXT NOT NULL UNIQUE,
		   role TEXT NOT NULL,
		   peer_aid TEXT NOT NULL,
		   goal TEXT NOT NULL,
		   request_cid TEXT NOT NULL DEFAULT '',
		   request_doc BLOB,
		   result_cid TEXT NOT NULL DEFAULT '',
		   result BLOB,
		   receipt BLOB,
		   review BLOB,
		   created_at TEXT NOT NULL,
		   updated_at TEXT NOT NULL
		 )`,
		// The per-interaction conversation log.
		`CREATE TABLE IF NOT EXISTS message (
		   seq INTEGER PRIMARY KEY AUTOINCREMENT,
		   interaction_id TEXT NOT NULL,
		   sender_aid TEXT NOT NULL,
		   kind TEXT NOT NULL,
		   body TEXT NOT NULL DEFAULT '',
		   created_at TEXT NOT NULL,
		   -- Sender-minted, so a redelivery can be told from a repetition.
		   -- The unique index over it is partial (see migrate): an older
		   -- sender mints none, and "unknown" is not an identity.
		   msg_id TEXT NOT NULL DEFAULT ''
		 )`,
		`CREATE INDEX IF NOT EXISTS idx_msg_ix ON message(interaction_id, seq)`,

		// Binary attachments carried by messages (images / media / archives). Bytes stored inline;
		// integrity pinned by cid = anetcid.SumRaw(data).
		`CREATE TABLE IF NOT EXISTS attachment (
		   seq INTEGER PRIMARY KEY AUTOINCREMENT,
		   interaction_id TEXT NOT NULL,
		   msg_seq INTEGER NOT NULL DEFAULT 0,
		   name TEXT NOT NULL DEFAULT '',
		   mime TEXT NOT NULL DEFAULT '',
		   size INTEGER NOT NULL DEFAULT 0,
		   cid TEXT NOT NULL DEFAULT '',
		   data BLOB,
		   created_at TEXT NOT NULL
		 )`,
		`CREATE INDEX IF NOT EXISTS idx_att_ix ON attachment(interaction_id, msg_seq, seq)`,
	}
	for _, q := range stmts {
		if _, err := s.db.Exec(q); err != nil {
			return fmt.Errorf("interactions: migrate: %w", err)
		}
	}
	for _, col := range []struct{ name, decl string }{
		{"msg_id", "TEXT NOT NULL DEFAULT ''"},
		{"metadata", "TEXT NOT NULL DEFAULT ''"},
	} {
		if err := addColumn(s.db, "message", col.name, col.decl); err != nil {
			return err
		}
	}
	if _, err := s.db.Exec(`CREATE UNIQUE INDEX IF NOT EXISTS idx_msg_dedupe
		 ON message(interaction_id, msg_id) WHERE msg_id != ''`); err != nil {
		return fmt.Errorf("interactions: migrate msg dedupe index: %w", err)
	}
	// FindByClientMessage looks a message up by its client message id through
	// this index: the expression is the one its query tests, character for
	// character. metadata comes after body in the row, so without the index
	// every lookup read every message body of the peer's tasks
	// (docs/notes/0035).
	if _, err := s.db.Exec(`CREATE INDEX IF NOT EXISTS idx_msg_client ON message(` + clientMsgIDExpr("") + `)`); err != nil {
		return fmt.Errorf("interactions: migrate client message index: %w", err)
	}
	for _, col := range interactionAdded {
		if err := addColumn(s.db, "interaction", col.name, col.decl); err != nil {
			return err
		}
	}
	if err := s.migrateStatusToState(); err != nil {
		return err
	}
	for _, q := range []string{
		`CREATE INDEX IF NOT EXISTS idx_ix_role_state ON interaction(role, state, seq)`,
		// Listing is newest state change first, with (state_at, seq) as the cursor.
		`CREATE INDEX IF NOT EXISTS idx_ix_state_at ON interaction(state_at, seq)`,
		`CREATE INDEX IF NOT EXISTS idx_ix_context ON interaction(context_id)`,
		// The payment sweeps (ListPayState) read the few quoted rows only.
		`CREATE INDEX IF NOT EXISTS idx_ix_pay ON interaction(role, pay_state)`,
		// HasOutboundWith, asked for a message whose task is not held.
		`CREATE INDEX IF NOT EXISTS idx_ix_peer ON interaction(peer_aid, role)`,
		// Listing (ListPage, Count) reads this index alone: it carries the
		// order and every column a ListFilter tests but receipt (see
		// listIndex; a context listing reads idx_ix_context). A row holds goal, request_doc and
		// result, megabytes each for a long message, and SQLite reaches a
		// later column only through the overflow pages of the ones before
		// it; a listing that sorted or filtered rows read all of that for
		// every match (docs/notes/0035: 13–33 s per ListTasks).
		`CREATE INDEX IF NOT EXISTS idx_ix_list ON interaction(state_at, seq, role, peer_aid, state, is_capability, trust, context_id)`,
		// The same columns led by the peer, for a listing of one peer (the
		// local A2A interface's every ListTasks and its count): read from
		// idx_ix_list, that listing and its count walked the index entries
		// of every task with every peer to find the few with this one.
		`CREATE INDEX IF NOT EXISTS idx_ix_peer_list ON interaction(peer_aid, state_at, seq, role, state, is_capability, trust, context_id)`,
	} {
		if _, err := s.db.Exec(q); err != nil {
			return fmt.Errorf("interactions: migrate index: %w", err)
		}
	}
	// The wire-2 receive tables (replay, peer_identity) live in the same
	// database so that the replay row and the business write can commit in
	// one transaction (A2A-DESIGN §3.6 step 10). See peers.go. The pending
	// queue and the outbound retry queue live here for the same reason.
	if err := s.migrateWire2(); err != nil {
		return err
	}
	if err := s.migratePending(); err != nil {
		return err
	}
	if err := s.migrateRefused(); err != nil {
		return err
	}
	return s.migrateOutbox()
}

// addColumn adds a column to an existing table; a duplicate-column error
// means the table is already migrated.
func addColumn(db *sql.DB, table, name, decl string) error {
	if _, err := db.Exec(`ALTER TABLE ` + table + ` ADD COLUMN ` + name + ` ` + decl); err != nil &&
		!strings.Contains(err.Error(), "duplicate column") {
		return fmt.Errorf("interactions: migrate add %s.%s: %w", table, name, err)
	}
	return nil
}

// hasColumn reports whether table has a column named name.
func hasColumn(db *sql.DB, table, name string) (bool, error) {
	rows, err := db.Query(`SELECT name FROM pragma_table_info(?)`, table)
	if err != nil {
		return false, err
	}
	defer rows.Close()
	for rows.Next() {
		var n string
		if err := rows.Scan(&n); err != nil {
			return false, err
		}
		if n == name {
			return true, nil
		}
	}
	return false, rows.Err()
}

// migrateStatusToState converts a store written before A2A-DESIGN §4.1: the
// status column (queued/ending/done/failed) is replaced by state.
//
//   - done → completed, failed → failed;
//   - queued and ending take the state the last text message implies: the
//     requester spoke last → working, the provider spoke last →
//     input-required, no message → submitted.
//
// state_at is the row's updated_at. The status column and its index are
// dropped afterwards, so no code can keep reading the old value.
func (s *Store) migrateStatusToState() error {
	has, err := hasColumn(s.db, "interaction", "status")
	if err != nil {
		return fmt.Errorf("interactions: migrate state: %w", err)
	}
	if !has {
		return nil
	}
	type old struct {
		id, role, peer, status, updated string
	}
	rows, err := s.db.Query(`SELECT id, role, peer_aid, status, updated_at FROM interaction`)
	if err != nil {
		return fmt.Errorf("interactions: migrate state: %w", err)
	}
	var list []old
	for rows.Next() {
		var o old
		if err := rows.Scan(&o.id, &o.role, &o.peer, &o.status, &o.updated); err != nil {
			rows.Close()
			return fmt.Errorf("interactions: migrate state: %w", err)
		}
		list = append(list, o)
	}
	rows.Close()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback() }()
	for _, o := range list {
		st := StateSubmitted
		switch o.status {
		case "done":
			st = StateCompleted
		case "failed":
			st = StateFailed
		default:
			var sender string
			err := tx.QueryRow(`SELECT sender_aid FROM message WHERE interaction_id=? AND kind='text'
			                    ORDER BY seq DESC LIMIT 1`, o.id).Scan(&sender)
			switch {
			case errors.Is(err, sql.ErrNoRows):
				st = StateSubmitted
			case err != nil:
				return fmt.Errorf("interactions: migrate state of %s: %w", o.id, err)
			default:
				// The requester is the peer of an inbound row and this node on
				// an outbound one.
				requesterSpoke := (sender == o.peer) == (Role(o.role) == RoleInbound)
				if requesterSpoke {
					st = StateWorking
				} else {
					st = StateInputRequired
				}
			}
		}
		at := int64(0)
		if t, perr := time.Parse(time.RFC3339Nano, o.updated); perr == nil {
			at = t.UnixMilli()
		}
		if _, err := tx.Exec(`UPDATE interaction SET state=?, state_at=?, state_seq=1 WHERE id=?`,
			string(st), at, o.id); err != nil {
			return fmt.Errorf("interactions: migrate state of %s: %w", o.id, err)
		}
	}
	for _, q := range []string{
		`DROP INDEX IF EXISTS idx_ix_role_status`,
		`ALTER TABLE interaction DROP COLUMN status`,
	} {
		if _, err := tx.Exec(q); err != nil {
			return fmt.Errorf("interactions: migrate state: %s: %w", q, err)
		}
	}
	return tx.Commit()
}

// New describes an interaction to record.
type New struct {
	ID           string
	Role         Role
	PeerAID      string
	Goal         string
	RequestCID   string
	RequestDoc   []byte
	ContextID    string
	Trust        string
	IsCapability bool
	TaskNonce    string
	PeerKEL      []byte // public / public_cap only
	PeerKeys     []byte // public / public_cap only
}

// Put records a new interaction in state submitted (idempotent on id: a repeat id is ignored, so a
// retried delegate does not create a duplicate). role/id/peerAID are required. requestDoc is the
// signed request TaskDoc bytes (Sum == requestCID).
func (s *Store) Put(id string, role Role, peerAID, goal, requestCID string, requestDoc []byte) error {
	return s.Create(New{ID: id, Role: role, PeerAID: peerAID, Goal: goal, RequestCID: requestCID, RequestDoc: requestDoc})
}

// Create records a new interaction in state submitted, with every
// creation-time field. Like Put it ignores a repeated id.
func (s *Store) Create(n New) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	return create(s.db, n, s.nowMS())
}

// create is Create against either the database handle or an open transaction.
func create(e execer, n New, nowMS int64) error {
	if n.ID == "" || n.Role == "" || n.PeerAID == "" {
		return fmt.Errorf("%w: id, role and peer required", ErrBadInput)
	}
	now := time.Now().UTC().Format(time.RFC3339Nano)
	capFlag := 0
	if n.IsCapability {
		capFlag = 1
	}
	_, err := e.Exec(
		`INSERT OR IGNORE INTO interaction(id,role,peer_aid,goal,state,state_at,state_seq,request_cid,request_doc,
		   context_id,trust,is_capability,task_nonce,peer_kel,peer_keys,created_at,updated_at)
		 VALUES(?,?,?,?,?,?,1,?,?,?,?,?,?,?,?,?,?)`,
		n.ID, string(n.Role), n.PeerAID, n.Goal, string(StateSubmitted), nowMS, n.RequestCID, n.RequestDoc,
		n.ContextID, n.Trust, capFlag, n.TaskNonce, n.PeerKEL, n.PeerKeys, now, now)
	return err
}

// SetState moves a non-terminal interaction to st. changed is false when
// the interaction is already terminal (the row is left as it is) or already
// in st; an absent row is ErrNotFound.
//
// A write to the same state is not a change: a status message that repeats
// the current state does not advance state_seq, so a waiter comparing
// sequence numbers does not wake for it.
func (s *Store) SetState(id string, st State) (changed bool, err error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	return setState(s.db, id, st, s.nowMS())
}

func setState(e execer, id string, st State, nowMS int64) (bool, error) {
	if id == "" || !st.Valid() {
		return false, fmt.Errorf("%w: id and a valid state required", ErrBadInput)
	}
	now := time.Now().UTC().Format(time.RFC3339Nano)
	q := `UPDATE interaction SET state=?, state_at=?, state_seq=state_seq+1, updated_at=?`
	if st.IsTerminal() {
		// §3.8: the requester's key material held for a public interaction
		// is kept only while the interaction is open.
		q += `, peer_kel=NULL, peer_keys=NULL`
	}
	q += ` WHERE id=? AND state NOT IN ` + terminalSQL + ` AND state != ?`
	res, err := e.Exec(q, string(st), nowMS, now, id, string(st))
	if err != nil {
		return false, err
	}
	n, _ := res.RowsAffected()
	if n > 0 {
		return true, nil
	}
	if _, err := getIX(e, id); err != nil {
		return false, err
	}
	return false, nil
}

// Finish describes a result write: the state it moves to and the result
// columns it stores.
type Finish struct {
	State     State
	Result    []byte
	ResultCID string
	Receipt   []byte
	// Verified is required rather than optional so that every path which
	// completes an interaction has to state what it knew about the
	// receipt. A caller with nothing to say passes VerificationUnknown.
	Verified Verification
	// Meta is the result's metadata object (JSON), or nil.
	Meta []byte
}

// Finish stores a result and moves the interaction to f.State in one guarded
// write. It returns ErrTerminal, and changes nothing, when the interaction
// is already terminal; this is what keeps a receipt from being stored on a
// canceled interaction. f.State may be non-terminal (a quote leaves a
// capability call waiting for input).
func (s *Store) Finish(id string, f Finish) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	return finish(s.db, id, f, s.nowMS())
}

// SetResult stores the deliverable, result CID and receipt and marks the interaction completed.
func (s *Store) SetResult(id string, result []byte, resultCID string, receipt []byte, verified Verification) error {
	return s.Finish(id, Finish{State: StateCompleted, Result: result, ResultCID: resultCID, Receipt: receipt, Verified: verified})
}

// SetFailed marks an interaction failed, keeping any diagnostic bytes.
func (s *Store) SetFailed(id string, detail []byte) error {
	return s.Finish(id, Finish{State: StateFailed, Result: detail, Verified: VerificationUnknown})
}

// finish is Store.Finish against either the database handle or an open transaction.
func finish(e execer, id string, f Finish, nowMS int64) error {
	if id == "" || !f.State.Valid() {
		return fmt.Errorf("%w: id and a valid state required", ErrBadInput)
	}
	now := time.Now().UTC().Format(time.RFC3339Nano)
	q := `UPDATE interaction SET state=?, state_at=?, state_seq=state_seq+1, result=?, result_cid=?, receipt=?,
	        receipt_verified=?, result_meta=?, updated_at=?`
	if f.State.IsTerminal() {
		q += `, peer_kel=NULL, peer_keys=NULL`
	}
	q += ` WHERE id=? AND state NOT IN ` + terminalSQL
	res, err := e.Exec(q, string(f.State), nowMS, f.Result, f.ResultCID, f.Receipt, string(f.Verified), string(f.Meta), now, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n > 0 {
		return nil
	}
	if _, err := getIX(e, id); err != nil {
		return err
	}
	return ErrTerminal
}

// SetLateResult stores a result that arrived for an interaction already in a
// terminal state (A2A-DESIGN §4.2: a result after a local cancel). The state
// is not changed, and nothing is written when a receipt is already stored.
// It reports whether it wrote.
func (s *Store) SetLateResult(id string, result []byte, resultCID string, receipt []byte, verified Verification) (bool, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	return setLateResult(s.db, id, result, resultCID, receipt, verified)
}

// setLateResult is Store.SetLateResult against either the database handle
// or an open transaction.
func setLateResult(e execer, id string, result []byte, resultCID string, receipt []byte, verified Verification) (bool, error) {
	now := time.Now().UTC().Format(time.RFC3339Nano)
	res, err := e.Exec(`UPDATE interaction SET result=?, result_cid=?, receipt=?, receipt_verified=?, updated_at=?
	   WHERE id=? AND state IN `+terminalSQL+` AND (receipt IS NULL OR length(receipt)=0)`,
		result, resultCID, receipt, string(verified), now, id)
	if err != nil {
		return false, err
	}
	n, _ := res.RowsAffected()
	return n > 0, nil
}

// SetPeerKeys records the requester's KEL and key set on a public or
// public_cap interaction that is still open (A2A-DESIGN §3.8).
func (s *Store) SetPeerKeys(id string, kel, keys []byte) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	return setPeerKeys(s.db, id, kel, keys)
}

func setPeerKeys(e execer, id string, kel, keys []byte) error {
	_, err := e.Exec(`UPDATE interaction SET peer_kel=COALESCE(?, peer_kel), peer_keys=COALESCE(?, peer_keys)
	   WHERE id=? AND state NOT IN `+terminalSQL, nilIfEmpty(kel), nilIfEmpty(keys), id)
	return err
}

func nilIfEmpty(b []byte) any {
	if len(b) == 0 {
		return nil
	}
	return b
}

// SetReview attaches the requester's signed review bytes to an outbound interaction.
func (s *Store) SetReview(id string, review []byte) error {
	if id == "" {
		return fmt.Errorf("%w: id required", ErrBadInput)
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	now := time.Now().UTC().Format(time.RFC3339Nano)
	res, err := s.db.Exec(`UPDATE interaction SET review=?, updated_at=? WHERE id=?`, review, now, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

// ixColumns is the shared SELECT column list for scanning an Interaction (keep in sync with scanRows).
const ixColumns = `seq,id,role,peer_aid,goal,state,state_at,state_seq,request_cid,request_doc,result_cid,result,receipt,review,
receipt_verified,end_req_by,end_acc_by,context_id,trust,is_capability,task_nonce,pay_state,pay_required,pay_auth_ids,
pay_payload,pay_receipts,quote_expires_at,peer_kel,peer_keys,result_meta,created_at,updated_at`

// Get returns one interaction by id.
func (s *Store) Get(id string) (*Interaction, error) {
	return getIX(s.db, id)
}

func getIX(e execer, id string) (*Interaction, error) {
	return scanOne(e.QueryRow(`SELECT `+ixColumns+` FROM interaction WHERE id=?`, id))
}

// MessageRecord is a message to store.
type MessageRecord struct {
	InteractionID string
	SenderAID     string
	Kind          string
	Body          string
	MsgID         string
	Metadata      []byte // JSON object, or nil
}

// AddMessage appends one entry to an interaction's conversation log with no sender-minted id and
// bumps the interaction's updated_at. Returns the new message seq.
func (s *Store) AddMessage(interactionID, senderAID, kind, body string) (int64, error) {
	seq, _, err := s.AddMessageID(interactionID, senderAID, kind, body, "")
	return seq, err
}

// AddMessageID records a message, ignoring one already stored
// under the same sender-minted id.
//
// stored is false for a redelivery, which the caller needs in order to
// tell "handled" from "handled again": a duplicate is not an error — the
// relay is at-least-once by design — but it must not become a second line
// in the transcript the receipt is taken over.
func (s *Store) AddMessageID(interactionID, senderAID, kind, body, msgID string) (seq int64, stored bool, err error) {
	return s.AddMessageRecord(MessageRecord{InteractionID: interactionID, SenderAID: senderAID, Kind: kind, Body: body, MsgID: msgID})
}

// AddMessageRecord is AddMessageID with metadata.
func (s *Store) AddMessageRecord(m MessageRecord) (seq int64, stored bool, err error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	return addMessage(s.db, m)
}

// addMessage is AddMessageRecord against either the database handle or an open transaction.
func addMessage(e execer, m MessageRecord) (seq int64, stored bool, err error) {
	if m.InteractionID == "" || m.SenderAID == "" || m.Kind == "" {
		return 0, false, fmt.Errorf("%w: interaction_id, sender and kind required", ErrBadInput)
	}
	now := time.Now().UTC().Format(time.RFC3339Nano)
	meta := string(m.Metadata)
	if m.MsgID != "" {
		// The partial unique index makes this the whole of the dedupe: a
		// second delivery of the same id inserts nothing and affects no
		// rows, and there is no read-then-write to race with.
		res, err := e.Exec(
			`INSERT OR IGNORE INTO message(interaction_id,sender_aid,kind,body,created_at,msg_id,metadata)
			 VALUES(?,?,?,?,?,?,?)`,
			m.InteractionID, m.SenderAID, m.Kind, m.Body, now, m.MsgID, meta)
		if err != nil {
			return 0, false, err
		}
		n, err := res.RowsAffected()
		if err != nil {
			return 0, false, err
		}
		if n == 0 {
			var prior int64
			if err := e.QueryRow(
				`SELECT seq FROM message WHERE interaction_id=? AND msg_id=?`,
				m.InteractionID, m.MsgID).Scan(&prior); err != nil {
				return 0, false, err
			}
			return prior, false, nil
		}
		_, _ = e.Exec(`UPDATE interaction SET updated_at=? WHERE id=?`, now, m.InteractionID)
		seq, err := res.LastInsertId()
		return seq, true, err
	}
	res, err := e.Exec(
		`INSERT INTO message(interaction_id,sender_aid,kind,body,created_at,metadata) VALUES(?,?,?,?,?,?)`,
		m.InteractionID, m.SenderAID, m.Kind, m.Body, now, meta)
	if err != nil {
		return 0, false, err
	}
	_, _ = e.Exec(`UPDATE interaction SET updated_at=? WHERE id=?`, now, m.InteractionID)
	seq, err = res.LastInsertId()
	return seq, true, err
}

// Messages returns an interaction's conversation log, oldest first.
func (s *Store) Messages(interactionID string) ([]Message, error) {
	rows, err := s.db.Query(
		`SELECT seq,interaction_id,sender_aid,kind,body,msg_id,metadata,created_at FROM message
		  WHERE interaction_id=? ORDER BY seq`,
		interactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Message
	for rows.Next() {
		var m Message
		if err := rows.Scan(&m.Seq, &m.InteractionID, &m.SenderAID, &m.Kind, &m.Body, &m.MsgID, &m.Metadata, &m.CreatedAt); err != nil {
			return nil, err
		}
		out = append(out, m)
	}
	return out, rows.Err()
}

// AddAttachment stores one binary attachment (with its bytes) against a message of an interaction.
func (s *Store) AddAttachment(interactionID string, msgSeq int64, a Attachment) error {
	if interactionID == "" || a.CID == "" {
		return fmt.Errorf("%w: interaction_id and attachment cid required", ErrBadInput)
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	return addAttachment(s.db, interactionID, msgSeq, a)
}

// AddAttachment is Store.AddAttachment inside the transaction: a received
// message's files commit with the message and its replay row, or not at
// all (A2A-DESIGN §3.6 step 10).
func (t *Tx) AddAttachment(interactionID string, msgSeq int64, a Attachment) error {
	if interactionID == "" || a.CID == "" {
		return fmt.Errorf("%w: interaction_id and attachment cid required", ErrBadInput)
	}
	return addAttachment(t.tx, interactionID, msgSeq, a)
}

func addAttachment(e execer, interactionID string, msgSeq int64, a Attachment) error {
	now := time.Now().UTC().Format(time.RFC3339Nano)
	_, err := e.Exec(
		`INSERT INTO attachment(interaction_id,msg_seq,name,mime,size,cid,data,created_at) VALUES(?,?,?,?,?,?,?,?)`,
		interactionID, msgSeq, a.Name, a.Mime, a.Size, a.CID, a.Data, now)
	return err
}

// Attachments returns the metadata (NO bytes) of all attachments in an interaction, oldest first.
func (s *Store) Attachments(interactionID string) ([]Attachment, error) {
	rows, err := s.db.Query(
		`SELECT seq,interaction_id,msg_seq,name,mime,size,cid,created_at FROM attachment WHERE interaction_id=? ORDER BY seq`,
		interactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Attachment
	for rows.Next() {
		var a Attachment
		if err := rows.Scan(&a.Seq, &a.InteractionID, &a.MsgSeq, &a.Name, &a.Mime, &a.Size, &a.CID, &a.CreatedAt); err != nil {
			return nil, err
		}
		out = append(out, a)
	}
	return out, rows.Err()
}

// AttachmentData returns one attachment WITH its bytes, by interaction + content CID.
func (s *Store) AttachmentData(interactionID, cid string) (*Attachment, error) {
	row := s.db.QueryRow(
		`SELECT seq,interaction_id,msg_seq,name,mime,size,cid,data,created_at FROM attachment WHERE interaction_id=? AND cid=? LIMIT 1`,
		interactionID, cid)
	var a Attachment
	err := row.Scan(&a.Seq, &a.InteractionID, &a.MsgSeq, &a.Name, &a.Mime, &a.Size, &a.CID, &a.Data, &a.CreatedAt)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	return &a, nil
}

// SetEndRequested records that `by` asked for the interaction to end. It is
// a historical field (A2A-DESIGN §4.1): the state is not changed by it.
func (s *Store) SetEndRequested(id, by string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	return setEndRequested(s.db, id, by)
}

// setEndRequested is SetEndRequested against either the database handle or an open transaction.
func setEndRequested(e execer, id, by string) error {
	if id == "" || by == "" {
		return fmt.Errorf("%w: id and by required", ErrBadInput)
	}
	now := time.Now().UTC().Format(time.RFC3339Nano)
	res, err := e.Exec(`UPDATE interaction SET end_req_by=?, updated_at=? WHERE id=?`, by, now, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

// List returns interactions in the given role with seq > sinceSeq, oldest first. If state is non-empty
// it filters to that state. limit ≤ 0 → 100. It is the seq-cursor scan used by callers that page
// through a whole role; listings shown to a person use ListPage, which is newest first.
func (s *Store) List(role Role, state State, sinceSeq int64, limit int) ([]*Interaction, error) {
	if limit <= 0 {
		limit = 100
	}
	q := `SELECT ` + ixColumns + ` FROM interaction WHERE role=? AND seq > ?`
	args := []any{string(role), sinceSeq}
	if state != "" {
		q += ` AND state=?`
		args = append(args, string(state))
	}
	q += ` ORDER BY seq LIMIT ?`
	args = append(args, limit)
	return s.query(q, args...)
}

// ListFilter selects interactions for ListPage and Count.
type ListFilter struct {
	Role   Role    // "" = both roles
	States []State // empty = any state
	// Active selects non-terminal interactions only.
	Active bool
	// ExcludeTrust leaves out interactions with these trust values.
	ExcludeTrust []string
	// ExcludeCapability leaves out capability-call interactions.
	ExcludeCapability bool
	ContextID         string
	PeerAID           string
	// UpdatedAfter selects interactions whose state_at is after this unix ms (0 = no bound).
	UpdatedAfter int64
	// HasReceipt selects interactions that carry a receipt.
	HasReceipt bool
	// Cursor is the Next value of the previous page; empty starts at the newest.
	Cursor string
	// Limit bounds the page; ≤ 0 means 100, and it is capped at 1000.
	Limit int
}

// Page is one page of ListPage. Next is empty on the last page.
type Page struct {
	Items []*Interaction
	Next  string
}

func (f ListFilter) where() (string, []any, error) {
	var conds []string
	var args []any
	if f.Role != "" {
		conds = append(conds, `role=?`)
		args = append(args, string(f.Role))
	}
	if len(f.States) > 0 {
		ph := make([]string, len(f.States))
		for i, st := range f.States {
			ph[i] = "?"
			args = append(args, string(st))
		}
		conds = append(conds, `state IN (`+strings.Join(ph, ",")+`)`)
	}
	if f.Active {
		conds = append(conds, `state NOT IN `+terminalSQL)
	}
	for _, t := range f.ExcludeTrust {
		conds = append(conds, `trust != ?`)
		args = append(args, t)
	}
	if f.ExcludeCapability {
		conds = append(conds, `is_capability = 0`)
	}
	if f.ContextID != "" {
		conds = append(conds, `context_id=?`)
		args = append(args, f.ContextID)
	}
	if f.PeerAID != "" {
		conds = append(conds, `peer_aid=?`)
		args = append(args, f.PeerAID)
	}
	if f.UpdatedAfter > 0 {
		conds = append(conds, `state_at > ?`)
		args = append(args, f.UpdatedAfter)
	}
	if f.HasReceipt {
		conds = append(conds, `receipt IS NOT NULL AND length(receipt) > 0`)
	}
	if f.Cursor != "" {
		at, seq, err := parseCursor(f.Cursor)
		if err != nil {
			return "", nil, err
		}
		// A row value, not "state_at < ? OR (state_at = ? AND seq < ?)":
		// SQLite reads it as one range of the listing index, in order.
		conds = append(conds, `(state_at, seq) < (?, ?)`)
		args = append(args, at, seq)
	}
	if len(conds) == 0 {
		return "", args, nil
	}
	return ` WHERE ` + strings.Join(conds, " AND "), args, nil
}

// ListPage returns interactions matching f, most recent state change first
// (A2A ListTasks order), one page at a time. The cursor is the (state_at,
// seq) of the last item, so a page boundary is stable while rows are added
// at the head.
//
// A page is read in two steps: the (state_at, seq) of its rows from an index
// (pageSQL), then those rows whole (rowsBySeq). The page boundary — whether
// there is a next page, and the cursor — is the first step's. Taken from the
// rows re-read in the second, a task that changed state in between moved
// the cursor to the head of the listing (the next page repeated this one),
// and a task deleted in between (PruneTerminal) left a full page looking like
// the last one, so the rest of the listing was never read.
func (s *Store) ListPage(f ListFilter) (Page, error) {
	limit := f.Limit
	if limit <= 0 {
		limit = 100
	}
	if limit > 1000 {
		limit = 1000
	}
	q, args, err := f.pageSQL(limit + 1)
	if err != nil {
		return Page{}, err
	}
	keys, err := s.pageKeys(q, args)
	if err != nil {
		return Page{}, err
	}
	var p Page
	if len(keys) > limit {
		keys = keys[:limit]
		last := keys[limit-1]
		p.Next = strconv.FormatInt(last.at, 10) + "." + strconv.FormatInt(last.seq, 10)
	}
	if betweenListSteps != nil {
		betweenListSteps()
	}
	if p.Items, err = s.rowsBySeq(keys); err != nil {
		return Page{}, err
	}
	return p, nil
}

// betweenListSteps, when set, runs between the two reads of ListPage. Tests
// only.
var betweenListSteps func()

// pageSQL is the first step of ListPage: the (state_at, seq) of up to limit
// rows matching f, in listing order, read from an index (listIndex).
func (f ListFilter) pageSQL(limit int) (string, []any, error) {
	where, args, err := f.where()
	if err != nil {
		return "", nil, err
	}
	return `SELECT state_at, seq FROM interaction` + f.listIndex() + where + ` ORDER BY state_at DESC, seq DESC LIMIT ?`,
		append(args, limit), nil
}

// countSQL is Count's query, read from the index as pageSQL is.
func (f ListFilter) countSQL() (string, []any, error) {
	f.Cursor = ""
	where, args, err := f.where()
	if err != nil {
		return "", nil, err
	}
	return `SELECT COUNT(*) FROM interaction` + f.listIndex() + where, args, nil
}

// listIndex pins a listing to an index, because left to itself SQLite
// takes the role or peer index for the equality and then reads each
// matching row — past its long columns — to filter and sort it. A context
// filter reads idx_ix_context: a context holds a handful of tasks, and the
// covering index would be read whole to find them. A listing of one peer
// reads idx_ix_peer_list, and any other idx_ix_list: both cover everything
// a filter tests but receipt and hold the listing order, the first within
// the peer's own tasks.
func (f ListFilter) listIndex() string {
	switch {
	case f.ContextID != "":
		return ` INDEXED BY idx_ix_context`
	case f.PeerAID != "":
		return ` INDEXED BY idx_ix_peer_list`
	}
	return ` INDEXED BY idx_ix_list`
}

// pageKey is a row of a page as the first step of ListPage reads it.
type pageKey struct{ at, seq int64 }

// pageKeys runs pageSQL's query.
func (s *Store) pageKeys(q string, args []any) ([]pageKey, error) {
	rows, err := s.db.Query(q, args...)
	if err != nil {
		return nil, err
	}
	var keys []pageKey
	for rows.Next() {
		var k pageKey
		if err := rows.Scan(&k.at, &k.seq); err != nil {
			rows.Close()
			return nil, err
		}
		keys = append(keys, k)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return keys, nil
}

// rowsBySeq reads the rows keys name, in their order.
func (s *Store) rowsBySeq(keys []pageKey) ([]*Interaction, error) {
	if len(keys) == 0 {
		return nil, nil
	}
	ph := make([]string, len(keys))
	in := make([]any, len(keys))
	for i, k := range keys {
		ph[i], in[i] = "?", k.seq
	}
	items, err := s.query(`SELECT `+ixColumns+` FROM interaction WHERE seq IN (`+strings.Join(ph, ",")+`)`, in...)
	if err != nil {
		return nil, err
	}
	bySeq := make(map[int64]*Interaction, len(items))
	for _, ix := range items {
		bySeq[ix.Seq] = ix
	}
	out := make([]*Interaction, 0, len(keys))
	for _, k := range keys {
		if ix := bySeq[k.seq]; ix != nil { // gone between the two reads: left out
			out = append(out, ix)
		}
	}
	return out, nil
}

// ListAll returns every interaction matching f, most recent state change
// first, by walking ListPage. The filter's Cursor and Limit are ignored.
func (s *Store) ListAll(f ListFilter) ([]*Interaction, error) {
	f.Cursor, f.Limit = "", 1000
	var out []*Interaction
	for {
		p, err := s.ListPage(f)
		if err != nil {
			return nil, err
		}
		out = append(out, p.Items...)
		if p.Next == "" {
			return out, nil
		}
		f.Cursor = p.Next
	}
}

// HasOutboundWith reports whether this node has ever asked peer for
// anything: an interaction with it in the outbound role, in any state.
func (s *Store) HasOutboundWith(peer string) (bool, error) {
	var one int
	err := s.db.QueryRow(`SELECT 1 FROM interaction WHERE peer_aid=? AND role=? LIMIT 1`, peer, string(RoleOutbound)).Scan(&one)
	if errors.Is(err, sql.ErrNoRows) {
		return false, nil
	}
	return err == nil, err
}

// Count returns how many interactions match f (Cursor and Limit ignored).
func (s *Store) Count(f ListFilter) (int, error) {
	q, args, err := f.countSQL()
	if err != nil {
		return 0, err
	}
	var n int
	err = s.db.QueryRow(q, args...).Scan(&n)
	return n, err
}

// ErrBadCursor is returned for a cursor ListPage did not produce.
var ErrBadCursor = errors.New("interactions: invalid page cursor")

func parseCursor(c string) (at, seq int64, err error) {
	a, b, ok := strings.Cut(c, ".")
	if !ok {
		return 0, 0, ErrBadCursor
	}
	if at, err = strconv.ParseInt(a, 10, 64); err != nil {
		return 0, 0, ErrBadCursor
	}
	if seq, err = strconv.ParseInt(b, 10, 64); err != nil {
		return 0, 0, ErrBadCursor
	}
	return at, seq, nil
}

func (s *Store) query(q string, args ...any) ([]*Interaction, error) {
	rows, err := s.db.Query(q, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []*Interaction
	for rows.Next() {
		ix, err := scanRows(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, ix)
	}
	return out, rows.Err()
}

type scanner interface{ Scan(dest ...any) error }

func scanOne(row scanner) (*Interaction, error) {
	ix, err := scanRows(row)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrNotFound
	}
	return ix, err
}

func scanRows(sc scanner) (*Interaction, error) {
	ix := &Interaction{}
	var role, state, verified, authIDs string
	var capFlag int
	if err := sc.Scan(&ix.Seq, &ix.ID, &role, &ix.PeerAID, &ix.Goal, &state, &ix.StateAt, &ix.StateSeq,
		&ix.RequestCID, &ix.RequestDoc, &ix.ResultCID, &ix.Result, &ix.Receipt, &ix.Review,
		&verified, &ix.EndReqBy, &ix.EndAccBy, &ix.ContextID, &ix.Trust, &capFlag, &ix.TaskNonce,
		&ix.PayState, &ix.PayRequired, &authIDs, &ix.PayPayload, &ix.PayReceipts, &ix.QuoteExpiresAt,
		&ix.PeerKEL, &ix.PeerKeys, &ix.ResultMeta, &ix.CreatedAt, &ix.UpdatedAt); err != nil {
		return nil, err
	}
	ix.Role = Role(role)
	ix.State = State(state)
	ix.ReceiptVerified = Verification(verified)
	ix.IsCapability = capFlag != 0
	if authIDs != "" {
		_ = json.Unmarshal([]byte(authIDs), &ix.PayAuthIDs)
	}
	return ix, nil
}
