// Package interactions is the v0.1 delegation store: a single durable log of the delegation
// interactions this daemon is part of, in EITHER role. It is what lets an agent be only intermittently
// online — the daemon persists inbound tasks (so a provider whose external agent is offline still
// accepts and stores work) and outbound delegations (so a requester can pull the result later), and
// both survive daemon restarts. Each interaction carries a multi-turn conversation (the message table).
//
// One SQLite table (+ a per-interaction message log), one row per interaction, discriminated by role:
//   - RoleInbound  — someone delegated a task TO us; we store it queued and converse via messages, and
//     once both sides end the task the provider issues its signed receipt over the transcript. anet
//     itself runs no model — the deliverable comes from the operator's EXTERNAL agent.
//   - RoleOutbound — WE delegated a task to a provider; we store it queued, converse, then pull the
//     final transcript + the provider's receipt (anet results) and may attach our signed review.
//
// interaction_id is generated by the REQUESTER at delegate time and carried on the wire, so both
// daemons key the same interaction by the same id — that shared id is what the receipt and the review
// bind to. Delivery is pull-by-cursor (monotonic seq), mirroring the im mailbox.
package interactions

import (
	"database/sql"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	_ "github.com/mattn/go-sqlite3"
)

// ErrBadInput is returned for missing required fields.
var ErrBadInput = errors.New("interactions: invalid input")

// ErrNotFound is returned when no interaction has the given id.
var ErrNotFound = errors.New("interactions: not found")

// Role is this daemon's side of an interaction.
type Role string

const (
	RoleInbound  Role = "inbound"  // someone delegated to us (we are the provider)
	RoleOutbound Role = "outbound" // we delegated to a provider (we are the requester)
)

// Status is an interaction's lifecycle state.
type Status string

const (
	StatusQueued Status = "queued" // active: the conversation is open (messages can flow both ways)
	StatusEnding Status = "ending" // one party proposed ending; awaiting the other's acceptance
	StatusDone   Status = "done"   // mutually ended: provider receipt present, requester may review
	StatusFailed Status = "failed" // processing failed
)

// Message kinds carried in the per-interaction conversation log.
const (
	MsgText       = "text"        // a normal chat message
	MsgEndRequest = "end_request" // a proposal to end the task
	MsgEndAccept  = "end_accept"  // acceptance of an end proposal (mutual end → provider issues the receipt)
)

// Message is one entry in an interaction's conversation log (v0.1 multi-turn chat). Chat messages are
// NOT individually signed (the Hub is trusted as the relay); the trust anchor is the end-of-task Receipt
// + Review, which ARE signed and Hub-verified.
type Message struct {
	Seq           int64
	InteractionID string
	SenderAID     string
	Kind          string // MsgText | MsgEndRequest | MsgEndAccept
	Body          string
	CreatedAt     string
}

// Attachment is one binary payload (image / media / archive) attached to a conversation message. The
// bytes are stored inline in SQLite (v0.1); integrity is pinned by CID = anetcid.SumRaw(Data). List/read
// helpers return metadata WITHOUT Data unless a data-loading accessor is used, to keep thread rendering
// and transcript building cheap.
type Attachment struct {
	Seq           int64
	InteractionID string
	MsgSeq        int64 // the message (message.seq) this attachment belongs to
	Name          string
	Mime          string
	Size          int64
	CID           string
	Data          []byte // populated only by AttachmentData
	CreatedAt     string
}

// Interaction is one stored delegation record.
type Interaction struct {
	Seq        int64  // local monotonic cursor
	ID         string // shared interaction_id (requester-generated)
	Role       Role
	PeerAID    string // the OTHER party: provider (outbound) or requester (inbound)
	Goal       string // the task text
	Status     Status
	RequestCID string // CID of the signed request TaskDoc (content anchor)
	RequestDoc []byte // the signed request TaskDoc bytes (Sum == RequestCID); lets the goal be re-verified
	ResultCID  string // CID of the result/transcript (content anchor)
	Result     []byte // the deliverable/transcript bytes (once done)
	Receipt    []byte // provider-signed receipt object (evidence.Receipt.Marshal), once done
	Review     []byte // requester-signed review object (evidence.Review.Marshal), once submitted (outbound)
	EndReqBy   string // AID that proposed ending the task ("" = none proposed yet)
	EndAccBy   string // AID that accepted an end proposal ("" = not yet accepted)
	CreatedAt  string // RFC3339Nano
	UpdatedAt  string // RFC3339Nano
}

// Store is the daemon's interaction log.
type Store struct {
	db *sql.DB
	mu sync.Mutex // serializes writes (single writer); reads run lock-free under WAL
}

// Open opens (creating if needed) an interactions store at dir (SQLite at dir/interactions.db).
func Open(dir string) (*Store, error) {
	if dir == "" {
		return nil, fmt.Errorf("interactions: dir required")
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return nil, fmt.Errorf("interactions: mkdir: %w", err)
	}
	db, err := sql.Open("sqlite3", filepath.Join(dir, "interactions.db")+"?_journal_mode=WAL&_synchronous=NORMAL&_busy_timeout=15000")
	if err != nil {
		return nil, fmt.Errorf("interactions: open db: %w", err)
	}
	s := &Store{db: db}
	if err := s.migrate(); err != nil {
		db.Close()
		return nil, err
	}
	return s, nil
}

// Close closes the db handle.
func (s *Store) Close() error { return s.db.Close() }

func (s *Store) migrate() error {
	stmts := []string{
		`CREATE TABLE IF NOT EXISTS interaction (
		   seq INTEGER PRIMARY KEY AUTOINCREMENT,
		   id TEXT NOT NULL UNIQUE,
		   role TEXT NOT NULL,
		   peer_aid TEXT NOT NULL,
		   goal TEXT NOT NULL,
		   status TEXT NOT NULL,
		   request_cid TEXT NOT NULL DEFAULT '',
		   request_doc BLOB,
		   result_cid TEXT NOT NULL DEFAULT '',
		   result BLOB,
		   receipt BLOB,
		   review BLOB,
		   end_req_by TEXT NOT NULL DEFAULT '',
		   end_acc_by TEXT NOT NULL DEFAULT '',
		   created_at TEXT NOT NULL,
		   updated_at TEXT NOT NULL
		 )`,
		`CREATE INDEX IF NOT EXISTS idx_ix_role_status ON interaction(role, status, seq)`,
		// The per-interaction conversation log (v0.1 multi-turn chat).
		`CREATE TABLE IF NOT EXISTS message (
		   seq INTEGER PRIMARY KEY AUTOINCREMENT,
		   interaction_id TEXT NOT NULL,
		   sender_aid TEXT NOT NULL,
		   kind TEXT NOT NULL,
		   body TEXT NOT NULL DEFAULT '',
		   created_at TEXT NOT NULL
		 )`,
		`CREATE INDEX IF NOT EXISTS idx_msg_ix ON message(interaction_id, seq)`,
		// Binary attachments carried by messages (images / media / archives). Bytes stored inline;
		// integrity pinned by cid = anetcid.SumRaw(data).
		`CREATE TABLE IF NOT EXISTS attachment (
		   seq INTEGER PRIMARY KEY AUTOINCREMENT,
		   interaction_id TEXT NOT NULL,
		   msg_seq INTEGER NOT NULL DEFAULT 0,
		   name TEXT NOT NULL DEFAULT '',
		   mime TEXT NOT NULL DEFAULT '',
		   size INTEGER NOT NULL DEFAULT 0,
		   cid TEXT NOT NULL DEFAULT '',
		   data BLOB,
		   created_at TEXT NOT NULL
		 )`,
		`CREATE INDEX IF NOT EXISTS idx_att_ix ON attachment(interaction_id, msg_seq, seq)`,
	}
	for _, q := range stmts {
		if _, err := s.db.Exec(q); err != nil {
			return fmt.Errorf("interactions: migrate: %w", err)
		}
	}
	// Best-effort add of the end-negotiation columns to a pre-existing interaction table (a duplicate
	// column error just means an already-migrated db).
	for _, col := range []string{"end_req_by", "end_acc_by"} {
		if _, err := s.db.Exec(`ALTER TABLE interaction ADD COLUMN ` + col + ` TEXT NOT NULL DEFAULT ''`); err != nil &&
			!strings.Contains(err.Error(), "duplicate column") {
			return fmt.Errorf("interactions: migrate add %s: %w", col, err)
		}
	}
	return nil
}

// Put records a new interaction (idempotent on id: a repeat id is ignored, so a retried delegate does
// not create a duplicate). role/id/peerAID are required. requestDoc is the signed request TaskDoc bytes
// (Sum == requestCID) — kept so the exact task can later be re-verified and its goal re-derived.
func (s *Store) Put(id string, role Role, peerAID, goal, requestCID string, requestDoc []byte) error {
	if id == "" || role == "" || peerAID == "" {
		return fmt.Errorf("%w: id, role and peer required", ErrBadInput)
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	now := time.Now().UTC().Format(time.RFC3339Nano)
	_, err := s.db.Exec(
		`INSERT OR IGNORE INTO interaction(id,role,peer_aid,goal,status,request_cid,request_doc,created_at,updated_at)
		 VALUES(?,?,?,?,?,?,?,?,?)`,
		id, string(role), peerAID, goal, string(StatusQueued), requestCID, requestDoc, now, now)
	return err
}

// SetResult attaches the deliverable + result CID + (optional) receipt and marks the interaction done.
func (s *Store) SetResult(id string, result []byte, resultCID string, receipt []byte) error {
	return s.finish(id, StatusDone, result, resultCID, receipt)
}

// SetFailed marks an interaction failed (e.g. the agent run errored), keeping any diagnostic bytes.
func (s *Store) SetFailed(id string, detail []byte) error {
	return s.finish(id, StatusFailed, detail, "", nil)
}

func (s *Store) finish(id string, st Status, result []byte, resultCID string, receipt []byte) error {
	if id == "" {
		return fmt.Errorf("%w: id required", ErrBadInput)
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	now := time.Now().UTC().Format(time.RFC3339Nano)
	res, err := s.db.Exec(
		`UPDATE interaction SET status=?, result=?, result_cid=?, receipt=?, updated_at=? WHERE id=?`,
		string(st), result, resultCID, receipt, now, id)
	if err != nil {
		return err
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

// SetReview attaches the requester's signed review bytes to an outbound interaction.
func (s *Store) SetReview(id string, review []byte) error {
	if id == "" {
		return fmt.Errorf("%w: id required", ErrBadInput)
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	now := time.Now().UTC().Format(time.RFC3339Nano)
	res, err := s.db.Exec(`UPDATE interaction SET review=?, updated_at=? WHERE id=?`, review, now, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

// ixColumns is the shared SELECT column list for scanning an Interaction (keep in sync with scanRows).
const ixColumns = `seq,id,role,peer_aid,goal,status,request_cid,request_doc,result_cid,result,receipt,review,end_req_by,end_acc_by,created_at,updated_at`

// Get returns one interaction by id.
func (s *Store) Get(id string) (*Interaction, error) {
	row := s.db.QueryRow(`SELECT `+ixColumns+` FROM interaction WHERE id=?`, id)
	return scanOne(row)
}

// AddMessage appends one entry to an interaction's conversation log and bumps the interaction's
// updated_at so it sorts to the top of the chat list. Returns the new message seq.
func (s *Store) AddMessage(interactionID, senderAID, kind, body string) (int64, error) {
	if interactionID == "" || senderAID == "" || kind == "" {
		return 0, fmt.Errorf("%w: interaction_id, sender and kind required", ErrBadInput)
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	now := time.Now().UTC().Format(time.RFC3339Nano)
	res, err := s.db.Exec(
		`INSERT INTO message(interaction_id,sender_aid,kind,body,created_at) VALUES(?,?,?,?,?)`,
		interactionID, senderAID, kind, body, now)
	if err != nil {
		return 0, err
	}
	_, _ = s.db.Exec(`UPDATE interaction SET updated_at=? WHERE id=?`, now, interactionID)
	return res.LastInsertId()
}

// Messages returns an interaction's conversation log, oldest first.
func (s *Store) Messages(interactionID string) ([]Message, error) {
	rows, err := s.db.Query(
		`SELECT seq,interaction_id,sender_aid,kind,body,created_at FROM message WHERE interaction_id=? ORDER BY seq`,
		interactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Message
	for rows.Next() {
		var m Message
		if err := rows.Scan(&m.Seq, &m.InteractionID, &m.SenderAID, &m.Kind, &m.Body, &m.CreatedAt); err != nil {
			return nil, err
		}
		out = append(out, m)
	}
	return out, rows.Err()
}

// AddAttachment stores one binary attachment (with its bytes) against a message of an interaction.
func (s *Store) AddAttachment(interactionID string, msgSeq int64, a Attachment) error {
	if interactionID == "" || a.CID == "" {
		return fmt.Errorf("%w: interaction_id and attachment cid required", ErrBadInput)
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	now := time.Now().UTC().Format(time.RFC3339Nano)
	_, err := s.db.Exec(
		`INSERT INTO attachment(interaction_id,msg_seq,name,mime,size,cid,data,created_at) VALUES(?,?,?,?,?,?,?,?)`,
		interactionID, msgSeq, a.Name, a.Mime, a.Size, a.CID, a.Data, now)
	return err
}

// Attachments returns the metadata (NO bytes) of all attachments in an interaction, oldest first.
func (s *Store) Attachments(interactionID string) ([]Attachment, error) {
	rows, err := s.db.Query(
		`SELECT seq,interaction_id,msg_seq,name,mime,size,cid,created_at FROM attachment WHERE interaction_id=? ORDER BY seq`,
		interactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Attachment
	for rows.Next() {
		var a Attachment
		if err := rows.Scan(&a.Seq, &a.InteractionID, &a.MsgSeq, &a.Name, &a.Mime, &a.Size, &a.CID, &a.CreatedAt); err != nil {
			return nil, err
		}
		out = append(out, a)
	}
	return out, rows.Err()
}

// AttachmentData returns one attachment WITH its bytes, by interaction + content CID.
func (s *Store) AttachmentData(interactionID, cid string) (*Attachment, error) {
	row := s.db.QueryRow(
		`SELECT seq,interaction_id,msg_seq,name,mime,size,cid,data,created_at FROM attachment WHERE interaction_id=? AND cid=? LIMIT 1`,
		interactionID, cid)
	var a Attachment
	err := row.Scan(&a.Seq, &a.InteractionID, &a.MsgSeq, &a.Name, &a.Mime, &a.Size, &a.CID, &a.Data, &a.CreatedAt)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	return &a, nil
}

// SetEndRequested records that `by` proposed ending the interaction and moves it to StatusEnding (only
// from an active/ending state — a done/failed interaction is not reopened).
func (s *Store) SetEndRequested(id, by string) error {
	if id == "" || by == "" {
		return fmt.Errorf("%w: id and by required", ErrBadInput)
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	now := time.Now().UTC().Format(time.RFC3339Nano)
	res, err := s.db.Exec(
		`UPDATE interaction SET end_req_by=?, status=?, updated_at=? WHERE id=? AND status IN ('queued','ending')`,
		by, string(StatusEnding), now, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

// SetEndAccepted records that `by` accepted the end proposal.
func (s *Store) SetEndAccepted(id, by string) error {
	if id == "" || by == "" {
		return fmt.Errorf("%w: id and by required", ErrBadInput)
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	now := time.Now().UTC().Format(time.RFC3339Nano)
	res, err := s.db.Exec(`UPDATE interaction SET end_acc_by=?, updated_at=? WHERE id=?`, by, now, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

// List returns interactions in the given role with seq > sinceSeq, oldest first. If status is non-empty
// it filters to that status (e.g. queued inbound = the provider's pending work). limit ≤ 0 → 100.
func (s *Store) List(role Role, status Status, sinceSeq int64, limit int) ([]*Interaction, error) {
	if limit <= 0 {
		limit = 100
	}
	q := `SELECT ` + ixColumns + ` FROM interaction WHERE role=? AND seq > ?`
	args := []any{string(role), sinceSeq}
	if status != "" {
		q += ` AND status=?`
		args = append(args, string(status))
	}
	q += ` ORDER BY seq LIMIT ?`
	args = append(args, limit)
	rows, err := s.db.Query(q, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []*Interaction
	for rows.Next() {
		ix, err := scanRows(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, ix)
	}
	return out, rows.Err()
}

type scanner interface{ Scan(dest ...any) error }

func scanOne(row scanner) (*Interaction, error) {
	ix, err := scanRows(row)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrNotFound
	}
	return ix, err
}

func scanRows(sc scanner) (*Interaction, error) {
	ix := &Interaction{}
	var role, status string
	if err := sc.Scan(&ix.Seq, &ix.ID, &role, &ix.PeerAID, &ix.Goal, &status,
		&ix.RequestCID, &ix.RequestDoc, &ix.ResultCID, &ix.Result, &ix.Receipt, &ix.Review,
		&ix.EndReqBy, &ix.EndAccBy, &ix.CreatedAt, &ix.UpdatedAt); err != nil {
		return nil, err
	}
	ix.Role = Role(role)
	ix.Status = Status(status)
	return ix, nil
}
