# shellcheck shell=bash
# remote.sh — 远端函数库。不要在本机运行,也不要拷到远端:common.sh 的 tn_remote 把它连同几行变量与
# 一行调用经 ssh 的 stdin 交给远端 `bash -s`,远端不留这个文件。
#
# 它能做的事被刻意限制在:
#   - 只写 <base>/<run-id>/ 之下(base:root 为 /opt/anet-testnet,否则 ~/anet-testnet);
#   - 只启动/停止名为 anet-testnet-<run-id>-* 的 systemd 瞬态单元(root),或自己 pid 文件里、
#     可执行文件位于 <base>/ 之下的进程(非 root);
#   - 端口被别的进程占着就拒绝,绝不去杀一个不是自己起的监听者。
# 系统模式下每个进程在 systemd 沙箱里跑:ProtectSystem=strict + ReadWritePaths=<run 目录> +
# ProtectHome + PrivateTmp。也就是说,即使二进制有缺陷,它能写的也只有测试网目录与私有 /tmp ——
# 生产 daemon 的数据目录、/tmp/anet-0 里的 daemon 指针与多 daemon 注册表,它看不见也写不到。
set -euo pipefail
export LC_ALL=C
umask 027

rt_die(){ echo "[$(hostname)] ERROR: $*" >&2; exit 1; }
rt_log(){ echo "[$(hostname)] $*" >&2; }

rt_init(){
  [[ "${TN_RUN_ID:-}" =~ ^[a-z0-9][a-z0-9-]{0,23}$ ]] || rt_die "bad run id: ${TN_RUN_ID:-}"
  [ "${TN_PREFIX:-}" = anet-testnet ] || rt_die "bad unit prefix: ${TN_PREFIX:-}"
  if [ "${TN_MODE:-auto}" = auto ]; then
    if [ "$(id -u)" = 0 ] && command -v systemd-run >/dev/null 2>&1; then TN_MODE=system; else TN_MODE=user; fi
  fi
  case "$TN_MODE" in
    system) [ "$(id -u)" = 0 ] || rt_die "system mode needs root"; TN_BASE=/opt/anet-testnet ;;
    user)   TN_BASE="$HOME/anet-testnet" ;;
    *)      rt_die "bad mode: $TN_MODE" ;;
  esac
  [ ! -L "$TN_BASE" ] || rt_die "$TN_BASE is a symlink; refusing"
  TN_RUNDIR="$TN_BASE/$TN_RUN_ID"
}

rt_unit(){ printf '%s-%s-%s' "$TN_PREFIX" "$TN_RUN_ID" "$1"; }

# rt_pid_ours PID: the process's executable lives under the testnet base directory.
rt_pid_ours(){
  local exe
  exe=$(readlink -f "/proc/$1/exe" 2>/dev/null) || return 1
  [[ "$exe" == "$TN_BASE/"* ]]
}

# rt_port_free PORT: nothing listens on PORT (TCP). Waits a little for our own process to go away.
rt_port_free(){
  local i line
  for i in 1 2 3 4 5 6 7 8 9 10; do
    line=$(ss -tlnH "( sport = :$1 )" 2>/dev/null || true)
    [ -z "$line" ] && return 0
    sleep 1
  done
  rt_die "port $1 is in use and not by a stopped testnet unit — refusing to touch it: $line"
}

rt_wait_http(){ # URL TRIES
  local i
  for ((i = 0; i < $2; i++)); do
    curl -sf --noproxy '*' -m 2 -o /dev/null "$1" </dev/null && return 0
    sleep 1
  done
  return 1
}

# rt_node_dir NAME: the node's directory, created with its private runtime dir.
rt_node_dir(){
  local d="$TN_RUNDIR/nodes/$1"
  mkdir -p "$d/home"
  mkdir -p -m 0700 "$d/xdg"
  chmod 0700 "$d/xdg"
  printf '%s' "$d"
}

# rt_write_launcher NAME DIR BIN ARGS...: DIR/run-NAME.sh, the one command both modes execute. The
# environment is rebuilt from scratch: HOME, ANET_DATA_DIR and XDG_RUNTIME_DIR point into DIR, proxy
# and identity-selection variables are removed, and secrets come from DIR/secret.env (0600), never argv.
rt_write_launcher(){
  local name=$1 dir=$2; shift 2
  local f="$dir/run-$name.sh"
  {
    echo '#!/bin/bash'
    echo "# generated by scripts/testnet/deploy.sh — run $TN_RUN_ID, unit $(rt_unit "$name")"
    printf 'cd %q || exit 1\n' "$dir"
    echo 'unset ANET_HOME ANET_ID http_proxy https_proxy HTTP_PROXY HTTPS_PROXY all_proxy ALL_PROXY'
    printf 'export HOME=%q ANET_DATA_DIR=%q XDG_RUNTIME_DIR=%q NO_PROXY=%q no_proxy=%q\n' \
      "$dir/home" "$dir/home/.anet" "$dir/xdg" '*' '*'
    echo 'if [ -f ./secret.env ]; then set -a; . ./secret.env; set +a; fi'
    printf 'exec'; printf ' %q' "$@"; printf '\n'
  } > "$f.tmp"
  chmod 0750 "$f.tmp"
  mv -f "$f.tmp" "$f"
}

# rt_stop NAME DIR: stop our unit / our pid. Never anything else.
rt_stop(){
  local name=$1 dir=$2 unit pf pid i
  unit=$(rt_unit "$name")
  if [ "$TN_MODE" = system ]; then
    if systemctl list-units --all --plain --no-legend "$unit.service" 2>/dev/null | grep -q .; then
      systemctl stop "$unit.service" 2>/dev/null || true
      systemctl reset-failed "$unit.service" 2>/dev/null || true
    fi
  fi
  pf="$dir/$name.pid"
  if [ -f "$pf" ]; then
    pid=$(cat "$pf" 2>/dev/null || true)
    if [[ "$pid" =~ ^[0-9]+$ ]] && rt_pid_ours "$pid"; then
      kill -TERM "$pid" 2>/dev/null || true
      for i in 1 2 3 4 5 6 7 8 9 10; do [ -d "/proc/$pid" ] || break; sleep 1; done
      if [ -d "/proc/$pid" ] && rt_pid_ours "$pid"; then kill -KILL "$pid" 2>/dev/null || true; fi
    fi
    rm -f "$pf"
  fi
}

# rt_start NAME DIR: run DIR/run-NAME.sh as unit anet-testnet-<run>-NAME (root) or detached (user).
rt_start(){
  local name=$1 dir=$2 unit log
  unit=$(rt_unit "$name"); log="$dir/$name.log"
  [ -x "$dir/run-$name.sh" ] || rt_die "no launcher for $name"
  rt_stop "$name" "$dir"
  if [ "$TN_MODE" = system ]; then
    systemd-run --quiet --unit="$unit" --description="anet testnet $TN_RUN_ID $name" \
      -p Restart=on-failure -p RestartSec=3 \
      -p WorkingDirectory="$dir" \
      -p ProtectSystem=strict -p ReadWritePaths="$TN_RUNDIR" -p ProtectHome=yes -p PrivateTmp=yes \
      -p NoNewPrivileges=yes -p ProtectKernelTunables=yes -p ProtectKernelModules=yes -p ProtectControlGroups=yes \
      -p MemoryMax=2G -p TasksMax=512 -p CPUQuota=200% -p Nice=5 \
      -p StandardOutput="append:$log" -p StandardError="append:$log" \
      /bin/bash "$dir/run-$name.sh" </dev/null
  else
    # Not `cd && setsid … &`: the & would background the whole list and $! would be a subshell.
    ( cd "$dir" || exit 1
      setsid env -i PATH=/usr/local/bin:/usr/bin:/bin nice -n 5 /bin/bash "$dir/run-$name.sh" \
        >>"$log" 2>&1 </dev/null &
      echo $! > "$dir/$name.pid" )
  fi
  rt_log "started $unit"
}

rt_fail_log(){ # NAME DIR MSG
  tail -n 20 "$2/$1.log" >&2 2>/dev/null || true
  rt_die "$3"
}

# ── entry points (called by deploy.sh / teardown.sh / bridge.sh) ─────────────────

# rt_prepare: create the run directory; print it (the scp destination) on stdout.
rt_prepare(){
  rt_init
  mkdir -p "$TN_BASE"
  chmod 0750 "$TN_BASE"
  mkdir -p "$TN_RUNDIR/bin" "$TN_RUNDIR/nodes"
  rm -rf -- "$TN_RUNDIR/bin/.incoming"
  mkdir -p "$TN_RUNDIR/bin/.incoming"
  echo "$TN_RUNDIR"
}

# rt_bin_sums: sha256 of the binaries already installed (lets deploy.sh skip unchanged files).
rt_bin_sums(){
  rt_init
  [ -d "$TN_RUNDIR/bin" ] || return 0
  ( cd "$TN_RUNDIR/bin" && for f in *; do [ -f "$f" ] && sha256sum -- "$f"; done ) 2>/dev/null || true
}

# rt_install_bins: verify .incoming against SHA256SUMS, then move into bin/.
rt_install_bins(){
  rt_init
  local inc="$TN_RUNDIR/bin/.incoming" f b
  [ -f "$inc/SHA256SUMS" ] || rt_die "no SHA256SUMS in $inc"
  # Only when binaries came: with every binary already current, .incoming holds just SHA256SUMS and
  # MANIFEST, and coreutils >= 9 answers --ignore-missing with nothing to check by failing ("no file was
  # verified") — which made every redeploy of an unchanged build die here.
  if [ -n "$(find "$inc" -maxdepth 1 -type f ! -name SHA256SUMS ! -name MANIFEST -print -quit)" ]; then
    ( cd "$inc" && sha256sum --quiet --ignore-missing -c SHA256SUMS ) || rt_die "checksum mismatch after transfer"
  fi
  for f in "$inc"/*; do
    [ -f "$f" ] || continue
    b=$(basename "$f")
    case "$b" in
      SHA256SUMS|MANIFEST) install -m 0644 "$f" "$TN_RUNDIR/bin/$b" ;;
      *) install -m 0755 "$f" "$TN_RUNDIR/bin/.$b.new" && mv -f "$TN_RUNDIR/bin/.$b.new" "$TN_RUNDIR/bin/$b" ;;
    esac
  done
  rm -rf -- "$inc"
  rt_log "binaries installed in $TN_RUNDIR/bin"
}

# rt_hub NAME BIND PORT ADMIN(0|1)
rt_hub(){
  rt_init
  local name=$1 bind=$2 port=$3 admin=${4:-0} d ad bin
  bin="$TN_RUNDIR/bin/anet-hub"; [ -x "$bin" ] || rt_die "missing $bin (deploy the binaries first)"
  d=$(rt_node_dir "$name"); mkdir -p "$d/data"
  rt_stop "$name" "$d"; rt_port_free "$port"
  rt_write_launcher "$name" "$d" "$bin" --addr "$bind:$port" --data "$d/data"
  rt_start "$name" "$d"
  rt_wait_http "http://$bind:$port/healthz" 30 || rt_fail_log "$name" "$d" "hub $name did not answer /healthz"
  rt_log "hub $name up at http://$bind:$port"
  if [ "$admin" = 1 ]; then
    [ -x "$TN_RUNDIR/bin/anet-hub-admin" ] || rt_die "missing anet-hub-admin"
    ad=$(rt_node_dir "$name/admin"); mkdir -p "$ad/data"
    if [ ! -s "$ad/secret.env" ]; then
      ( umask 077; printf 'ADMIN_TOKEN=%s\n' "$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')" > "$ad/secret.env" )
    fi
    rt_stop "$name-admin" "$ad"; rt_port_free $((port + 50))
    rt_write_launcher "$name-admin" "$ad" "$TN_RUNDIR/bin/anet-hub-admin" \
      --addr "127.0.0.1:$((port + 50))" --hub-data "$d/data" --data "$ad/data" \
      --harvest-every 0 --snapshot-every 0
    rt_start "$name-admin" "$ad"
    rt_wait_http "http://127.0.0.1:$((port + 50))/admin/healthz" 20 \
      || rt_fail_log "$name-admin" "$ad" "hub admin $name did not answer"
    rt_log "hub admin $name on 127.0.0.1:$((port + 50)) (token in $ad/secret.env, not printed)"
  fi
}

# rt_daemon NAME PORT HUB_URL BIN PEER_BIND PEER_PORT PEER_DIAL CONFIG_B64 REWRITE(0|1)
# PEER_PORT "-" = no anetpeer. CONFIG_B64 "" = the minimal config below.
rt_daemon(){
  rt_init
  local name=$1 port=$2 hub=$3 binname=$4 pbind=$5 pport=$6 pdial=$7 cfg64=${8:-} rewrite=${9:-0}
  local d bin cfg modules="" i
  bin="$TN_RUNDIR/bin/$binname"; [ -x "$bin" ] || rt_die "missing $bin (deploy the binaries first)"
  d=$(rt_node_dir "$name"); mkdir -p "$d/home/.anet"; chmod 0700 "$d/home/.anet"
  if [ "$pport" != - ]; then
    [ -x "$TN_RUNDIR/bin/anetpeer" ] || rt_die "missing anetpeer"
    # sun_path is 108 bytes; a longer path fails at bind with "invalid argument".
    [ ${#d} -lt 95 ] || rt_die "socket path under $d is too long for a unix socket"
    rt_stop "$name-peer" "$d"; rt_port_free "$pport"
    rm -f "$d/peer.sock"   # a stale socket would satisfy the wait below even if the new peer failed
    rt_write_launcher "$name-peer" "$d" "$TN_RUNDIR/bin/anetpeer" \
      --socket "$d/peer.sock" --peer "$pbind:$pport" --advertise "$pdial:$pport" --rendezvous "$hub"
    rt_start "$name-peer" "$d"
    for i in 1 2 3 4 5 6 7 8 9 10; do [ -S "$d/peer.sock" ] && break; sleep 1; done
    [ -S "$d/peer.sock" ] || rt_fail_log "$name-peer" "$d" "anetpeer for $name did not open its socket"
    modules=$(printf ',\n "modules": {"p2p": {"socket": "%s"}}' "$d/peer.sock")
  fi
  cfg="$d/home/.anet/config.json"
  if [ ! -f "$cfg" ] || [ "$rewrite" = 1 ]; then
    if [ -n "$cfg64" ]; then
      printf '%s' "$cfg64" | base64 -d > "$cfg.tmp"
    else
      printf '{\n "control_addr": "127.0.0.1:%s",\n "hub_url": "%s",\n "name": "tn-%s"%s\n}\n' \
        "$port" "$hub" "$name" "$modules" > "$cfg.tmp"
    fi
    chmod 0600 "$cfg.tmp"; mv -f "$cfg.tmp" "$cfg"
  else
    rt_log "$name: keeping the existing config.json (REWRITE_CONFIG=1 to replace it)"
  fi
  # The local A2A interface (module/a2a, on by default) at control port + 50, inside the testnet's
  # block. Unpinned, a first start takes the first free loopback port from 43811 (module/a2a/addr.go).
  local a2a="$d/home/.anet/modules/a2a"
  mkdir -p "$a2a"; chmod 0700 "$d/home/.anet/modules" "$a2a"
  if [ ! -s "$a2a/a2a_addr.txt" ] || [ "$rewrite" = 1 ]; then
    ( umask 077; printf '127.0.0.1:%s\n' $((port + 50)) > "$a2a/a2a_addr.txt" )
  fi
  rt_stop "$name" "$d"; rt_port_free "$port"; rt_port_free $((port + 50))
  rt_write_launcher "$name" "$d" "$bin" daemon
  rt_start "$name" "$d"
  rt_wait_http "http://127.0.0.1:$port/ping" 30 || rt_fail_log "$name" "$d" "daemon $name did not answer /ping"
  rt_log "daemon $name up on 127.0.0.1:$port (hub $hub)"
}

# rt_official NAME PORT BACKEND_ARGS...: the anet-official backend on 127.0.0.1:PORT+1. The daemon
# half is a separate rt_daemon call.
rt_official_backend(){
  rt_init
  local name=$1 port=$2; shift 2
  local bin="$TN_RUNDIR/bin/anet-official" bd
  [ -x "$bin" ] || rt_die "missing $bin — ANet/cmd/anet-official not built yet"
  bd=$(rt_node_dir "$name/backend")
  rt_stop "$name-backend" "$bd"; rt_port_free $((port + 1))
  rt_write_launcher "$name-backend" "$bd" "$bin" "$@"
  rt_start "$name-backend" "$bd"
  sleep 2
  if [ "$TN_MODE" = system ]; then
    systemctl is-active -q "$(rt_unit "$name-backend").service" || rt_fail_log "$name-backend" "$bd" "backend exited"
  else
    [ -d "/proc/$(cat "$bd/$name-backend.pid")" ] || rt_fail_log "$name-backend" "$bd" "backend exited"
  fi
  rt_log "official backend $name on 127.0.0.1:$((port + 1))"
}

# rt_register NAME PORT HUB_URL DISPLAY [P2P_ADDR]: /hub-register through the control API, then, when
# the node has an anetpeer, /p2p-advertise of its dial address. anetpeer uses the hub as rendezvous but
# holds no key, so it cannot publish the address itself; without this no peer ever dials it and every
# delegation goes through the hubs. The bearer token is read into a 0600 header file inside the node dir,
# so it never appears in a command line.
rt_register(){
  rt_init
  local name=$1 port=$2 hub=$3 display=$4 p2p=${5:-} d tok out
  d="$TN_RUNDIR/nodes/$name"; tok="$d/home/.anet/control_token.txt"
  [ -s "$tok" ] || rt_die "$name has no control token yet"
  ( umask 077; printf 'Authorization: Bearer %s\n' "$(tr -d '\n' < "$tok")" > "$d/.ctl-header" )
  out=$(curl -s --noproxy '*' -m 60 -H @"$d/.ctl-header" -H 'Content-Type: application/json' \
        -d "{\"hub\":\"$hub\",\"name\":\"$display\"}" "http://127.0.0.1:$port/hub-register" </dev/null || true)
  case "$out" in
    *'"error"'*|'') rm -f "$d/.ctl-header"; rt_die "$name: hub-register failed: $(printf '%s' "${out:-no answer}" | head -c 300)" ;;
    *registered*)   rt_log "$name registered at $hub as $display" ;;
    *)              rt_log "$name: hub-register answered: $(printf '%s' "$out" | head -c 300)" ;;
  esac
  if [ -n "$p2p" ]; then
    out=$(curl -s --noproxy '*' -m 60 -H @"$d/.ctl-header" -H 'Content-Type: application/json' \
          -d "{\"addr\":\"$p2p\"}" "http://127.0.0.1:$port/p2p-advertise" </dev/null || true)
    case "$out" in
      *published*) rt_log "$name advertised its peer address $p2p at $hub" ;;
      *)           rm -f "$d/.ctl-header"; rt_die "$name: p2p-advertise $p2p failed: $(printf '%s' "${out:-no answer}" | head -c 300)" ;;
    esac
  fi
  rm -f "$d/.ctl-header"
}

# rt_aid NAME PORT: print the daemon's AID from GET /status (token via a 0600 header file, as above).
rt_aid(){
  rt_init
  local name=$1 port=$2 d tok out
  d="$TN_RUNDIR/nodes/$name"; tok="$d/home/.anet/control_token.txt"
  [ -s "$tok" ] || rt_die "$name has no control token yet"
  ( umask 077; printf 'Authorization: Bearer %s\n' "$(tr -d '\n' < "$tok")" > "$d/.ctl-header" )
  out=$(curl -s --noproxy '*' -m 10 -H @"$d/.ctl-header" "http://127.0.0.1:$port/status" </dev/null || true)
  rm -f "$d/.ctl-header"
  printf '%s' "$out" | rt_json_field aid
}

# rt_json_field KEY: a top-level string field of the JSON object on stdin ("" when absent or not JSON).
rt_json_field(){
  python3 -c 'import sys, json
try: print(json.load(sys.stdin).get(sys.argv[1], ""))
except Exception: print("")' "$1"
}

# rt_hub_identity URL: print the hub's AID.
rt_hub_identity(){
  curl -s --noproxy '*' -m 10 "$1/hub/identity" </dev/null | rt_json_field aid
}

# rt_federation NAME CONFIG_B64 URL: write federation.json into the hub's data dir and restart it.
rt_federation(){
  rt_init
  local name=$1 cfg64=$2 url=$3 d
  d="$TN_RUNDIR/nodes/$name"
  [ -d "$d/data" ] && [ -x "$d/run-$name.sh" ] || rt_die "hub $name is not deployed here"
  printf '%s' "$cfg64" | base64 -d > "$d/data/federation.json.tmp"
  mv -f "$d/data/federation.json.tmp" "$d/data/federation.json"
  rt_start "$name" "$d"
  rt_wait_http "$url/healthz" 30 || rt_fail_log "$name" "$d" "hub $name did not come back after federation"
  rt_log "hub $name restarted with federation.json"
}

# rt_restart UNIT_NAME / rt_halt UNIT_NAME: restart or stop one testnet process by its short name
# (d1a, hub1, d1a-peer, hub1-admin, off2-backend), found by its launcher under this run's nodes/.
rt_launcher_dir(){
  local l
  l=$(find "$TN_RUNDIR/nodes" -maxdepth 3 -name "run-$1.sh" -type f 2>/dev/null | head -1)
  [ -n "$l" ] || rt_die "no launcher for $1 in run $TN_RUN_ID"
  dirname "$l"
}
rt_restart(){ rt_init; [[ "$1" =~ ^[a-z0-9-]+$ ]] || rt_die "bad name"; rt_start "$1" "$(rt_launcher_dir "$1")"; }
rt_halt(){    rt_init; [[ "$1" =~ ^[a-z0-9-]+$ ]] || rt_die "bad name"; rt_stop  "$1" "$(rt_launcher_dir "$1")"; rt_log "stopped $(rt_unit "$1")"; }

# rt_file NAME RELPATH: print a file from a node dir (config.json, control_token.txt, logs) on stdout.
rt_file(){
  rt_init
  local f="$TN_RUNDIR/nodes/$1/$2"
  [[ "$2" != *..* ]] || rt_die "bad path"
  [ -f "$f" ] || rt_die "no such file: $f"
  cat -- "$f"
}

# rt_status: what the testnet is running on this host.
rt_status(){
  rt_init
  echo "host=$(hostname) mode=$TN_MODE base=$TN_BASE"
  [ -d "$TN_BASE" ] || { echo "  (no testnet directory)"; return 0; }
  local rd l name dir st
  for rd in "$TN_BASE"/*/; do
    [ -d "$rd/nodes" ] || continue
    echo "  run $(basename "$rd")"
    [ -f "$rd/bin/MANIFEST" ] && sed 's/^/    manifest: /' "$rd/bin/MANIFEST" | head -8
    while IFS= read -r l; do
      name=$(basename "$l" .sh); name=${name#run-}; dir=$(dirname "$l")
      if [ "$TN_MODE" = system ]; then
        st=$(systemctl is-active "$TN_PREFIX-$(basename "$rd")-$name.service" 2>/dev/null || true)
      elif [ -f "$dir/$name.pid" ] && [ -d "/proc/$(cat "$dir/$name.pid")" ]; then st=running
      else st=stopped; fi
      printf '    %-14s %s\n' "$name" "${st:-unknown}"
    done < <(find "$rd/nodes" -maxdepth 3 -name 'run-*.sh' 2>/dev/null | sort)
  done
  if [ "$TN_MODE" = system ]; then
    echo "  units:"; systemctl list-units --all --plain --no-legend "$TN_PREFIX-*" 2>/dev/null | sed 's/^/    /'
  fi
}

# rt_teardown SCOPE DRY: SCOPE "all" or a run id. Stops anet-testnet-* units and our own pids, then
# deletes <base> (or <base>/<run>) — and nothing else.
rt_teardown(){
  rt_init
  local scope=${1:-all} dry=${2:-0} pat u pf pid target
  if [ "$scope" = all ]; then pat="$TN_PREFIX-"; target="$TN_BASE"
  else
    [[ "$scope" =~ ^[a-z0-9][a-z0-9-]{0,23}$ ]] || rt_die "bad run id: $scope"
    pat="$TN_PREFIX-$scope-"; target="$TN_BASE/$scope"
  fi
  run(){ if [ "$dry" = 1 ]; then echo "  [dry-run] $*"; else "$@"; fi; }
  if [ "$TN_MODE" = system ]; then
    for u in $(systemctl list-units --all --plain --no-legend "$TN_PREFIX-*" 2>/dev/null | awk '{print $1}'); do
      [[ "$u" == "$pat"* ]] || continue
      echo "  stop $u"
      run systemctl stop "$u" || true
      run systemctl reset-failed "$u" 2>/dev/null || true
    done
  fi
  if [ -d "$target" ]; then
    while IFS= read -r pf; do
      pid=$(cat "$pf" 2>/dev/null || true)
      if [[ "$pid" =~ ^[0-9]+$ ]] && rt_pid_ours "$pid"; then echo "  kill $pid ($pf)"; run kill -TERM "$pid" || true; fi
    done < <(find "$target" -name '*.pid' -type f 2>/dev/null)
    [ "$dry" = 1 ] || sleep 2
    # Stragglers: any process whose executable is under the target directory.
    for pid in $(pgrep -f -- "$target/" 2>/dev/null || true); do
      local exe; exe=$(readlink -f "/proc/$pid/exe" 2>/dev/null || true)
      [[ "$exe" == "$target/"* ]] || continue
      echo "  kill straggler $pid ($exe)"; run kill -KILL "$pid" || true
    done
    local real; real=$(readlink -f "$target")
    case "$real" in
      /opt/anet-testnet|/opt/anet-testnet/*|"$HOME/anet-testnet"|"$HOME/anet-testnet/"*) ;;
      *) rt_die "refusing to delete $real" ;;
    esac
    echo "  rm -rf $real"
    run rm -rf --one-file-system -- "$real"
  else
    echo "  nothing at $target"
  fi
}
